-- generated by org.heigit.ohsome.now.statsservice.TopicSqlGenerator at 2023-12-12T13:52:58.411979Z


CREATE TABLE IF NOT EXISTS prod.topic_place
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `place_current`      String, 
    `place_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW prod.mv__stats_to_topic_place TO prod.topic_place
AS SELECT
(
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['place'] as  `place_current`, 
    tags_before['place'] as `place_before`
)
FROM prod.stats
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-12T17:52:58Z')
    AND
    (
        
        place_current  != '' OR place_before != '' 
    )