-- generated by org.heigit.ohsome.now.statsservice.TopicSqlGenerator at 2023-12-12T13:18:52.061905Z


INSERT into int.topic_place
SELECT
    changeset_timestamp,
    user_id,
    hashtag,
    country_iso_a3,
    
    tags['place'] as  `place_current`, 
    tags_before['place'] as `place_before`
FROM
    int.stats;
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-12T17:18:51Z')
    AND
    (
        
    place_current  != '' OR place_before != '' 
    )