-- generated by org.heigit.ohsome.now.statsservice.TopicSqlGenerator at 2023-12-13T16:10:29.993976Z


CREATE TABLE IF NOT EXISTS int.topic_waterway__7
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `waterway_current`      String, 
    `waterway_before`       String
    ,
    length          Int64,
    length_delta    Int64
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_to_topic_waterway TO int.topic_waterway
AS SELECT
(
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['waterway'] as  `waterway_current`, 
    tags_before['waterway'] as `waterway_before`
    ,
    length,
    length_delta
)
FROM int.stats
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-13T20:10:29Z')
    AND
    (
        
        waterway_current  != '' OR waterway_before != '' 
    )