-- generated by org.heigit.ohsome.now.statsservice.TopicSqlGenerator at 2023-12-13T16:10:29.989079Z


INSERT into int.topic_healthcare
SELECT
    changeset_timestamp,
    user_id,
    hashtag,
    country_iso_a3,
    
    tags['healthcare'] as  `healthcare_current`, 
    tags_before['healthcare'] as `healthcare_before`,

    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
     
FROM
    int.stats
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-13T20:10:29Z')
    AND
    (
        
        healthcare_current  != '' OR healthcare_before != '' 
        OR

        amenity_current  != '' OR amenity_before != '' 
    )