-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-14T15:39:21.359414Z


INSERT into int.topic_amenity_2
SELECT
    changeset_timestamp,
    user_id,
    hashtag,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
     
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-14T19:39:21Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
    )