-- generated by org.heigit.ohsome.now.statsservice.TopicSqlGenerator at 2023-12-12T14:02:12.891713Z


CREATE TABLE IF NOT EXISTS int.topic_healthcare
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `healthcare_current`      String, 
    `healthcare_before`       String,

    `amenity_current`      String, 
    `amenity_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_to_topic_healthcare TO int.topic_healthcare
AS SELECT
(
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['healthcare'] as  `healthcare_current`, 
    tags_before['healthcare'] as `healthcare_before`,

    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
    
)
FROM int.stats
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-12T18:02:12Z')
    AND
    (
        
        healthcare_current  != '' OR healthcare_before != '' 
        OR

        amenity_current  != '' OR amenity_before != '' 
    )