-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.549080873Z


CREATE TABLE IF NOT EXISTS prod.topic_education_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `amenity_current`      String, 
    `amenity_before`       String,

    `building_current`      String, 
    `building_before`       String
    ,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    INDEX topic_education_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
    INDEX topic_education_3_skip_user_id_ix user_id TYPE bloom_filter(0.25) GRANULARITY 1
)
    ENGINE = MergeTree
    PRIMARY KEY (
                 has_hashtags,
                 toStartOfDay(changeset_timestamp)
                )
    ORDER BY (
              has_hashtags,
              toStartOfDay(changeset_timestamp),
              geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
              changeset_timestamp
             )
;

CREATE MATERIALIZED VIEW prod.mv__all_stats_3_to_topic_education_3
TO prod.topic_education_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`
    ,
    
    `has_hashtags`,
    `centroid`
FROM prod.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-05-14T10:40:00Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        building_current  != '' OR building_before != '' 
    )
;