-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-07T10:51:34.937137Z


INSERT into prod.topic_wash_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['man_made'] as  `man_made_current`, 
    tags_before['man_made'] as `man_made_before`
    , 
    has_hashtags
FROM
    prod.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-03-07T10:34:18Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        man_made_current  != '' OR man_made_before != '' 
    )
;