-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-29T12:10:58.865213Z


CREATE TABLE IF NOT EXISTS prod.topic_building_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `building_current`      String, 
    `building_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW prod.mv__stats_2_to_topic_building_2
TO prod.topic_building_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`
    
FROM prod.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2024-01-29T14:10:58Z')
    AND
    (
        
        building_current  != '' OR building_before != '' 
    )
;