-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.455280147Z


INSERT into prod.topic_amenity_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
    , 
    has_hashtags,
    centroid
FROM
    prod.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-14T10:40:00Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
    )
;