-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.094476351Z


-- for hashtags endpoint
CREATE TABLE IF NOT EXISTS prod.hashtag_aggregation_3
(
    `hashtag`           String,
    `count`             UInt64
)
    ENGINE = MergeTree
    PRIMARY KEY( count )
;

-- we have to refresh the whole table periodically
-- because the count is *not* an incremental operation
CREATE MATERIALIZED VIEW prod.mv__all_stats_3_to_hashtag_aggregation_3
REFRESH EVERY 1 MINUTE
TO prod.hashtag_aggregation_3
AS
SELECT
    arrayJoin(hashtags) AS hashtag,
    count(*) as count
FROM prod.all_stats_3
GROUP BY hashtag
;    