-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-29T12:10:58.865669Z


INSERT into prod.topic_building_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`
     
FROM
    prod.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2024-01-29T14:10:58Z')
    AND
    (
        
        building_current  != '' OR building_before != '' 
    )