-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T16:06:02.955808Z


CREATE TABLE IF NOT EXISTS prod.topic_poi_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `amenity_current`      String, 
    `amenity_before`       String,

    `shop_current`      String, 
    `shop_before`       String,

    `craft_current`      String, 
    `craft_before`       String,

    `office_current`      String, 
    `office_before`       String,

    `leisure_current`      String, 
    `leisure_before`       String,

    `aeroway_current`      String, 
    `aeroway_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW prod.mv__stats_2_to_topic_poi_2
TO prod.topic_poi_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['shop'] as  `shop_current`, 
    tags_before['shop'] as `shop_before`,

    tags['craft'] as  `craft_current`, 
    tags_before['craft'] as `craft_before`,

    tags['office'] as  `office_current`, 
    tags_before['office'] as `office_before`,

    tags['leisure'] as  `leisure_current`, 
    tags_before['leisure'] as `leisure_before`,

    tags['aeroway'] as  `aeroway_current`, 
    tags_before['aeroway'] as `aeroway_before`
    
FROM prod.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-20T20:06:02Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        shop_current  != '' OR shop_before != '' 
        OR

        craft_current  != '' OR craft_before != '' 
        OR

        office_current  != '' OR office_before != '' 
        OR

        leisure_current  != '' OR leisure_before != '' 
        OR

        aeroway_current  != '' OR aeroway_before != '' 
    )
;