-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-07T10:51:34.963418Z


-- for metadata endpoint
ALTER TABLE prod.all_stats_3 ADD PROJECTION timestamp_projection_3 (
    SELECT
        changeset_timestamp
    ORDER BY
        changeset_timestamp
);

ALTER TABLE prod.all_stats_3 MATERIALIZE PROJECTION timestamp_projection_3;