-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-07T10:51:34.907088Z


INSERT into prod.topic_lulc_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`,

    tags['natural'] as  `natural_current`, 
    tags_before['natural'] as `natural_before`,

    tags['waterway'] as  `waterway_current`, 
    tags_before['waterway'] as `waterway_before`
    ,
        area,
        area_delta, 
    has_hashtags
FROM
    prod.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-03-07T10:34:18Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
        OR

        natural_current  != '' OR natural_before != '' 
        OR

        waterway_current  != '' OR waterway_before != '' 
    )
;