-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.584499816Z


CREATE TABLE IF NOT EXISTS prod.topic_lulc_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `landuse_current`      String, 
    `landuse_before`       String,

    `natural_current`      String, 
    `natural_before`       String,

    `waterway_current`      String, 
    `waterway_before`       String
    ,
    area          Int64,
    area_delta    Int64,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    INDEX topic_lulc_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
    INDEX topic_lulc_3_skip_user_id_ix user_id TYPE bloom_filter(0.25) GRANULARITY 1
)
    ENGINE = MergeTree
    PRIMARY KEY (
                 has_hashtags,
                 toStartOfDay(changeset_timestamp)
                )
    ORDER BY (
              has_hashtags,
              toStartOfDay(changeset_timestamp),
              geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
              changeset_timestamp
             )
;

CREATE MATERIALIZED VIEW prod.mv__all_stats_3_to_topic_lulc_3
TO prod.topic_lulc_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`,

    tags['natural'] as  `natural_current`, 
    tags_before['natural'] as `natural_before`,

    tags['waterway'] as  `waterway_current`, 
    tags_before['waterway'] as `waterway_before`
    ,
        area,
        area_delta,
    
    `has_hashtags`,
    `centroid`
FROM prod.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-05-14T10:40:00Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
        OR

        natural_current  != '' OR natural_before != '' 
        OR

        waterway_current  != '' OR waterway_before != '' 
    )
;