-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.188270360Z


-- for metadata endpoint
ALTER TABLE prod.all_stats_3 ADD PROJECTION timestamp_projection_3 (
SELECT
    min(changeset_timestamp),
    max(changeset_timestamp)
);

ALTER TABLE prod.all_stats_3 MATERIALIZE PROJECTION timestamp_projection_3;