-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T16:06:02.952760Z


CREATE TABLE IF NOT EXISTS prod.topic_lulc_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `landuse_current`      String, 
    `landuse_before`       String,

    `natural_current`      String, 
    `natural_before`       String,

    `waterway_current`      String, 
    `waterway_before`       String
    ,
    area          Int64,
    area_delta    Int64
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW prod.mv__stats_2_to_topic_lulc_2
TO prod.topic_lulc_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`,

    tags['natural'] as  `natural_current`, 
    tags_before['natural'] as `natural_before`,

    tags['waterway'] as  `waterway_current`, 
    tags_before['waterway'] as `waterway_before`
    ,
        area,
        area_delta
FROM prod.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-20T20:06:02Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
        OR

        natural_current  != '' OR natural_before != '' 
        OR

        waterway_current  != '' OR waterway_before != '' 
    )
;