-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-14T10:29:20.540043945Z


INSERT into prod.topic_commercial_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['shop'] as  `shop_current`, 
    tags_before['shop'] as `shop_before`
    , 
    has_hashtags,
    centroid
FROM
    prod.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-14T10:40:00Z')
    AND
    (
        
        shop_current  != '' OR shop_before != '' 
    )
;