-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-14T15:48:20.322809Z


INSERT into prod.topic_amenity_2
SELECT changeset_timestamp,
       hashtag,
       user_id,
       country_iso_a3,

       tags['amenity']        as `amenity_current`,
       tags_before['amenity'] as `amenity_before`

FROM prod.stats_2
WHERE changeset_timestamp <= parseDateTimeBestEffort('2023-12-14T12:15:43Z')
  AND (
    amenity_current != '' OR amenity_before != ''
    )