-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-04-22T10:55:11.647621523Z


INSERT into prod.topic_body_of_water_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['water'] as  `water_current`, 
    tags_before['water'] as `water_before`
     
FROM
    prod.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2024-04-22T14:55:11Z')
    AND
    (
        
        water_current  != '' OR water_before != '' 
    )