-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-07-22T09:53:59.530951504Z


INSERT into prod.topic_commercial_3
SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['shop'] as  `shop_current`, 
    tags_before['shop'] as `shop_before`,
    
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`
FROM
    prod.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-07-22T13:53:59Z')
    AND
    (
        shop_current  != '' OR shop_before != '' 
    )
;