-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-29T12:10:58.877611Z


INSERT into prod.topic_highway_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['highway'] as  `highway_current`, 
    tags_before['highway'] as `highway_before`
    ,
    length,
    length_delta 
FROM
    prod.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2024-01-29T14:10:58Z')
    AND
    (
        
        highway_current  != '' OR highway_before != '' 
    )