-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-04-22T10:55:11.646296135Z


CREATE TABLE IF NOT EXISTS prod.topic_body_of_water_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `water_current`      String, 
    `water_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW prod.mv__stats_2_to_topic_body_of_water_2
TO prod.topic_body_of_water_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['water'] as  `water_current`, 
    tags_before['water'] as `water_before`
    
FROM prod.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2024-04-22T14:55:11Z')
    AND
    (
        water_current  != '' OR water_before != '' 
    )
;