-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-09T13:22:49.024643354Z


CREATE TABLE IF NOT EXISTS int.topic_poi_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `amenity_current`      String, 
    `amenity_before`       String,

    `shop_current`      String, 
    `shop_before`       String,

    `craft_current`      String, 
    `craft_before`       String,

    `office_current`      String, 
    `office_before`       String,

    `leisure_current`      String, 
    `leisure_before`       String,

    `aeroway_current`      String, 
    `aeroway_before`       String
    ,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    INDEX topic_poi_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
    INDEX topic_poi_3_skip_user_id_ix user_id TYPE bloom_filter(0.25) GRANULARITY 1
)
    ENGINE = MergeTree
    PRIMARY KEY (
                 has_hashtags,
                 toStartOfDay(changeset_timestamp)
                )
    ORDER BY (
              has_hashtags,
              toStartOfDay(changeset_timestamp),
              geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
              changeset_timestamp
             )
;

CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_topic_poi_3
TO int.topic_poi_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['shop'] as  `shop_current`, 
    tags_before['shop'] as `shop_before`,

    tags['craft'] as  `craft_current`, 
    tags_before['craft'] as `craft_before`,

    tags['office'] as  `office_current`, 
    tags_before['office'] as `office_before`,

    tags['leisure'] as  `leisure_current`, 
    tags_before['leisure'] as `leisure_before`,

    tags['aeroway'] as  `aeroway_current`, 
    tags_before['aeroway'] as `aeroway_before`
    ,
    
    `has_hashtags`,
    `centroid`
FROM int.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-05-05T00:00:00Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        shop_current  != '' OR shop_before != '' 
        OR

        craft_current  != '' OR craft_before != '' 
        OR

        office_current  != '' OR office_before != '' 
        OR

        leisure_current  != '' OR leisure_before != '' 
        OR

        aeroway_current  != '' OR aeroway_before != '' 
    )
;