-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-21T14:21:01.037608Z


INSERT into int.topic_place_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['place'] as  `place_current`, 
    tags_before['place'] as `place_before`
    , 
    has_hashtags
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-03-21T18:21:00Z')
    AND
    (
        
        place_current  != '' OR place_before != '' 
    )
;