-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-15T09:50:41.266265279Z


CREATE TABLE IF NOT EXISTS int.topic_landuse_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `landuse_current`      String, 
    `landuse_before`       String
    ,
    area          Int64,
    area_delta    Int64
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_2_to_topic_landuse_2
TO int.topic_landuse_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`
    ,
        area,
        area_delta
FROM int.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-15T13:50:41Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
    )
;