-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-15T12:52:21.245277384Z


INSERT into int.topic_sanitation_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['man_made'] as  `man_made_current`, 
    tags_before['man_made'] as `man_made_before`,

    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`,

    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
     
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-15T13:52:21Z')
    AND
    (
        
        man_made_current  != '' OR man_made_before != '' 
        OR

        building_current  != '' OR building_before != '' 
        OR

        amenity_current  != '' OR amenity_before != '' 
    )