-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-04-29T19:06:47.725873254Z


INSERT into int.topic_amenity_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
    , 
    has_hashtags,
    centroid
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-04-29T19:15:00Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
    )
;