-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-21T13:02:19.387578954Z


INSERT into int.topic_body_of_water_3
SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['water'] as  `water_current`, 
    tags_before['water'] as `water_before`,
    
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-21T13:15:00Z')
    AND
    (
        water_current  != '' OR water_before != '' 
    )
;