-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-21T13:02:19.458588401Z


INSERT into int.topic_wash_3
SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['man_made'] as  `man_made_current`, 
    tags_before['man_made'] as `man_made_before`,
    
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-21T13:15:00Z')
    AND
    (
        amenity_current  != '' OR amenity_before != '' 
        OR
        man_made_current  != '' OR man_made_before != '' 
    )
;