-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T16:06:02.958230Z


CREATE TABLE IF NOT EXISTS int.topic_wash_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `amenity_current`      String, 
    `amenity_before`       String,

    `man_made_current`      String, 
    `man_made_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_2_to_topic_wash_2
TO int.topic_wash_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['man_made'] as  `man_made_current`, 
    tags_before['man_made'] as `man_made_before`
    
FROM int.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-20T20:06:02Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        man_made_current  != '' OR man_made_before != '' 
    )
;