-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-23T14:19:22.296096497Z


INSERT into int.topic_highway_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['highway'] as  `highway_current`, 
    tags_before['highway'] as `highway_before`
    ,
    length,
    length_delta 
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2024-01-23T18:19:22Z')
    AND
    (
        
        highway_current  != '' OR highway_before != '' 
    )