-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-21T13:02:19.271265683Z


INSERT INTO int.all_stats_user_3
SELECT
    `changeset_id`,
    `changeset_timestamp`,
    `hashtags`,
    `editor`,
    `user_id`,
    `osm_id`,
    `tags`,
    `tags_before`,
    `area`,
    `area_delta`,
    `length`,
    `length_delta`,
    `map_feature_edit`,
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`,
    `country_iso_a3`
FROM int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-21T13:15:00Z')
;