-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T15:45:02.855400Z


CREATE TABLE IF NOT EXISTS int.topic_education_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `amenity_current`      String, 
    `amenity_before`       String,

    `building_current`      String, 
    `building_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_2_to_topic_education_2
TO int.topic_education_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`,

    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`
    
FROM int.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2023-12-20T19:45:02Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
        OR

        building_current  != '' OR building_before != '' 
    )
;