-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-04-29T19:06:47.670501980Z


-- for metadata endpoint
ALTER TABLE int.all_stats_3 ADD PROJECTION timestamp_projection_3 (
SELECT
    min(changeset_timestamp),
    max(changeset_timestamp)
);

ALTER TABLE int.all_stats_3 MATERIALIZE PROJECTION timestamp_projection_3;