-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-21T14:21:00.958287Z


CREATE TABLE IF NOT EXISTS int.topic_body_of_water_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `water_current`      String, 
    `water_before`       String
    ,
    `has_hashtags`        Bool
)
    ENGINE = MergeTree
    PRIMARY KEY(has_hashtags, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_topic_body_of_water_3
TO int.topic_body_of_water_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['water'] as  `water_current`, 
    tags_before['water'] as `water_before`
    ,
    
    `has_hashtags`
FROM int.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-03-21T18:21:00Z')
    AND
    (
        
        water_current  != '' OR water_before != '' 
    )
;