-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-09T13:22:48.826085419Z


-- for metadata endpoint
ALTER TABLE int.all_stats_3 ADD PROJECTION timestamp_projection_3 (
SELECT
    min(changeset_timestamp),
    max(changeset_timestamp)
);

ALTER TABLE int.all_stats_3 MATERIALIZE PROJECTION timestamp_projection_3;