-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-04-29T19:06:47.621536581Z


-- for hashtags endpoint
CREATE TABLE IF NOT EXISTS int.hashtag_aggregation_3
(
    `hashtag`           String,
    `count`             UInt64
)
    ENGINE = MergeTree
    PRIMARY KEY( count )
;

-- we have to refresh the whole table periodically
-- because the count is *not* an incremental operation
CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_hashtag_aggregation_3
REFRESH EVERY 1 MINUTE
TO int.hashtag_aggregation_3
AS
SELECT
    arrayJoin(hashtags) AS hashtag,
    count(*) as count
FROM int.all_stats_3
GROUP BY hashtag
;    