-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-15T09:50:41.266723362Z


INSERT into int.topic_landuse_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`
    ,
        area,
        area_delta 
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-15T13:50:41Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
    )