-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T15:45:02.857172Z


INSERT into int.topic_financial_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
     
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-20T19:45:02Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
    )