-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-07T10:51:34.903108Z


CREATE TABLE IF NOT EXISTS int.topic_lulc_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `landuse_current`      String, 
    `landuse_before`       String,

    `natural_current`      String, 
    `natural_before`       String,

    `waterway_current`      String, 
    `waterway_before`       String
    ,
    area          Int64,
    area_delta    Int64,
    `has_hashtags`        Bool
)
    ENGINE = MergeTree
    PRIMARY KEY(has_hashtags, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_topic_lulc_3
TO int.topic_lulc_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['landuse'] as  `landuse_current`, 
    tags_before['landuse'] as `landuse_before`,

    tags['natural'] as  `natural_current`, 
    tags_before['natural'] as `natural_before`,

    tags['waterway'] as  `waterway_current`, 
    tags_before['waterway'] as `waterway_before`
    ,
        area,
        area_delta,
    
    `has_hashtags`
FROM int.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-03-07T10:34:18Z')
    AND
    (
        
        landuse_current  != '' OR landuse_before != '' 
        OR

        natural_current  != '' OR natural_before != '' 
        OR

        waterway_current  != '' OR waterway_before != '' 
    )
;