-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-09T13:22:49.037215211Z


INSERT into int.topic_highway_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['highway'] as  `highway_current`, 
    tags_before['highway'] as `highway_before`
    ,
    length,
    length_delta, 
    has_hashtags,
    centroid
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-05-05T00:00:00Z')
    AND
    (
        
        highway_current  != '' OR highway_before != '' 
    )
;