-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-22T16:25:41.151248577Z


CREATE TABLE IF NOT EXISTS int.topic_building_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `building_current`      String, 
    `building_before`       String
    
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_2_to_topic_building_2
TO int.topic_building_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['building'] as  `building_current`, 
    tags_before['building'] as `building_before`
    
FROM int.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2024-01-22T20:25:41Z')
    AND
    (
        
        building_current  != '' OR building_before != '' 
    )
;