-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2023-12-20T15:45:02.853897Z


INSERT into int.topic_commercial_2
SELECT
    changeset_timestamp,
    hashtag,
    user_id,
    country_iso_a3,
    
    tags['shop'] as  `shop_current`, 
    tags_before['shop'] as `shop_before`
     
FROM
    int.stats_2
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2023-12-20T19:45:02Z')
    AND
    (
        
        shop_current  != '' OR shop_before != '' 
    )