-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-21T13:02:19.448185686Z


CREATE TABLE IF NOT EXISTS int.topic_road_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `highway_current`      String, 
    `highway_before`       String,
    
    `length`              Int64,
    `length_delta`        Int64,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    `h3_r3`               Nullable(UInt64),
    `h3_r6`               Nullable(UInt64),
    INDEX topic_road_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
    INDEX topic_road_3_skip_cts_ix country_iso_a3 TYPE set(0) GRANULARITY 1
)
ENGINE = MergeTree
PRIMARY KEY (
    has_hashtags,
    toStartOfDay(changeset_timestamp)
)
ORDER BY (
    has_hashtags,
    toStartOfDay(changeset_timestamp),
    geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
    changeset_timestamp
)
;

CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_topic_road_3
TO int.topic_road_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['highway'] as  `highway_current`, 
    tags_before['highway'] as `highway_before`,
    
    `length`,
    `length_delta`,
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`
FROM int.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-05-21T13:15:00Z')
    AND
    (
        highway_current  != '' OR highway_before != '' 
    )
;

-- USER MV --

CREATE TABLE IF NOT EXISTS int.topic_user_road_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `highway_current`      String, 
    `highway_before`       String,
    
    `length`              Int64,
    `length_delta`        Int64,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    `h3_r3`               Nullable(UInt64),
    `h3_r6`               Nullable(UInt64),
INDEX topic_user_road_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
INDEX topic_user_road_3_skip_cts_ix country_iso_a3 TYPE set(0) GRANULARITY 1
)
ENGINE = MergeTree
PRIMARY KEY (
    user_id,
    has_hashtags,
    toStartOfDay(changeset_timestamp)
)
ORDER BY (
    user_id,
    has_hashtags,
    toStartOfDay(changeset_timestamp),
    geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
    changeset_timestamp
)
;

CREATE MATERIALIZED VIEW int.mv__topic_road_3_to_topic_user_road_3
TO int.topic_user_road_3
AS SELECT 
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    `highway_current`, 
    `highway_before`,
    
    `length`,
    `length_delta`,
    `has_hashtags`,
    `centroid`,
    `h3_r3`,
    `h3_r6`
FROM int.topic_road_3
;