-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-05-09T13:22:49.001309316Z


CREATE TABLE IF NOT EXISTS int.topic_healthcare_3
(
    `changeset_timestamp` DateTime('UTC'),
    `hashtags`            Array(String),
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `healthcare_current`      String, 
    `healthcare_before`       String,

    `amenity_current`      String, 
    `amenity_before`       String
    ,
    `has_hashtags`        Bool,
    `centroid`            Tuple(x Nullable(Float64), y Nullable(Float64)),
    INDEX topic_healthcare_3_skip_ht_ix hashtags TYPE set(0) GRANULARITY 1,
    INDEX topic_healthcare_3_skip_user_id_ix user_id TYPE bloom_filter(0.25) GRANULARITY 1
)
    ENGINE = MergeTree
    PRIMARY KEY (
                 has_hashtags,
                 toStartOfDay(changeset_timestamp)
                )
    ORDER BY (
              has_hashtags,
              toStartOfDay(changeset_timestamp),
              geohashEncode(coalesce(centroid.x, 0), coalesce(centroid.y, 0), 2),
              changeset_timestamp
             )
;

CREATE MATERIALIZED VIEW int.mv__all_stats_3_to_topic_healthcare_3
TO int.topic_healthcare_3
AS SELECT
    `changeset_timestamp`,
    `hashtags`,
    `user_id`,
    `country_iso_a3`,
    
    tags['healthcare'] as  `healthcare_current`, 
    tags_before['healthcare'] as `healthcare_before`,

    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
    ,
    
    `has_hashtags`,
    `centroid`
FROM int.all_stats_3
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2025-05-05T00:00:00Z')
    AND
    (
        
        healthcare_current  != '' OR healthcare_before != '' 
        OR

        amenity_current  != '' OR amenity_before != '' 
    )
;