-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2025-03-21T14:21:00.950425Z


INSERT into int.topic_amenity_3
SELECT
    changeset_timestamp,
    hashtags,
    user_id,
    country_iso_a3,
    
    tags['amenity'] as  `amenity_current`, 
    tags_before['amenity'] as `amenity_before`
    , 
    has_hashtags
FROM
    int.all_stats_3
WHERE
    changeset_timestamp <= parseDateTimeBestEffort('2025-03-21T18:21:00Z')
    AND
    (
        
        amenity_current  != '' OR amenity_before != '' 
    )
;