-- generated by org.heigit.ohsome.now.statsservice.SqlGenerator at 2024-01-23T14:19:22.295709295Z


CREATE TABLE IF NOT EXISTS int.topic_highway_2
(
    `changeset_timestamp` DateTime,
    `hashtag`             String,
    `user_id`             Int32,
    `country_iso_a3`      Array(String),
    
    `highway_current`      String, 
    `highway_before`       String
    ,
    length          Int64,
    length_delta    Int64
)
    ENGINE = MergeTree
    PRIMARY KEY( hashtag, changeset_timestamp)
;

CREATE MATERIALIZED VIEW int.mv__stats_2_to_topic_highway_2
TO int.topic_highway_2
AS SELECT
    `changeset_timestamp`,
    `hashtag`,
    `user_id`,
    `country_iso_a3`,
    
    tags['highway'] as  `highway_current`, 
    tags_before['highway'] as `highway_before`
    ,
    length,
    length_delta
FROM int.stats_2
WHERE
    changeset_timestamp > parseDateTimeBestEffort('2024-01-23T18:19:22Z')
    AND
    (
        
        highway_current  != '' OR highway_before != '' 
    )
;