package org.heigit.ohsome.now.statsservice

import org.heigit.ohsome.now.statsservice.topic.TopicDefinition
import org.heigit.ohsome.now.statsservice.topic.createTableDDL
import org.heigit.ohsome.now.statsservice.topic.topics
import org.junit.jupiter.api.Test
import java.io.File
import java.time.Instant.now


class TopicSqlGenerator {

    val path = "sql_topics_generated/"


    @Test
    fun `create topic SQL for all topics`() {

        topics.values.forEach(::writeSql)

    }


    fun writeSql(definition: TopicDefinition) {

        val comment = "-- generated by " + TopicSqlGenerator::class.qualifiedName + " at " + now().toString() + "\n\n\n"

        val sql = createTableDDL(definition)

        val text = comment + sql

        val filename = "topic_" + definition.topicName + ".sql"

        File(path + filename).writeText(text)
    }


}


