package org.heigit.ohsome.now.statsservice

import org.heigit.ohsome.now.statsservice.topic.*
import org.junit.jupiter.api.Test
import java.io.File
import java.time.Instant.now
import java.time.temporal.ChronoUnit.HOURS
import java.time.temporal.ChronoUnit.SECONDS


class TopicSqlGenerator {

    //TODO: user generation only and not table name anymore

    private val currentTableName = statsTableName
    private val currentGeneration = schemaVersion


    private val fourHoursLater = now()
        .plus(4, HOURS)
        .truncatedTo(SECONDS)
        .toString()

    private val path = "sql_topics_generated/"


    @Test
    fun `create topic SQL for all topics`() = topics
        .values
        .forEach(::writeSql)


    private fun writeSql(definition: TopicDefinition) {
        writeDDLs(definition, "int", currentTableName, currentGeneration)
        writeInserts(definition, "int", currentTableName, currentGeneration)

        writeDDLs(definition, "prod", currentTableName, currentGeneration)
        writeInserts(definition, "prod", currentTableName, currentGeneration)
    }


    private fun writeDDLs(definition: TopicDefinition, stage: String, tableName: String, generation: String) =
        writeSqlToFile("DDL", definition, stage) {
            createDDLCommands(definition, stage, tableName, generation)
        }


    private fun writeInserts(definition: TopicDefinition, stage: String, tableName: String, generation: String) =
        writeSqlToFile("INSERT", definition, stage) {
            createInsertCommands(definition, stage, tableName, generation)
        }


    private fun writeSqlToFile(prefix: String, definition: TopicDefinition, stage: String, command: () -> String) = this
        .getFile(prefix, definition, stage)
        .writeText(command())


    private fun createDDLCommands(definition: TopicDefinition, stage: String, tableName: String, generation: String) =
        comment() +
                createTableDDL(definition, stage, generation) + "\n\n" +
                createMvDdl(definition, fourHoursLater, stage, tableName, generation)


    private fun createInsertCommands(
        definition: TopicDefinition,
        stage: String,
        tableName: String,
        generation: String
    ) = comment() +
            createInsertStatement(definition, fourHoursLater, stage, tableName, generation)


    private fun comment() = "-- generated by " + TopicSqlGenerator::class.qualifiedName +
            " at " + now().toString() + "\n\n\n"


    private fun getFile(prefix: String, definition: TopicDefinition, stage: String): File {
        val filename = stage + "/" + stage + "_" + prefix + "__topic_" + definition.topicName + ".sql"
        return File(path + filename)
    }


}


